config/routes.rb
Rails.application.routes.draw do
  resources :outcomes
  resources :incomes
  resources :categories
  root "home#index"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :outcomes
  belongs_to :user

  validates :name, presence: true
end

app/models/income.rb
class Income < ApplicationRecord
  validates :total, presence: true
  validates :description, presence: true, length: {maximum: 140}
end

app/models/outcome.rb
class Outcome < ApplicationRecord
  belongs_to :user
  belongs_to :category

  validates :total, presence: true
  validates :description, presence: true, length: {maximum: 140}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :incomes
  has_many :outcomes

  has_many :categories

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_home

  def set_home
    if user_signed_in?
      @income_sum = current_user.incomes.sum(:total)
      @outcome_sum = current_user.outcomes.sum(:total)
      @balance = @income_sum - @outcome_sum
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  layout 'home'

  # GET /categories
  # GET /categories.json
  def index
    @categories = current_user.categories.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = current_user.categories.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = current_user.categories.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_path, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = current_user.categories.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'home'

  def index
  end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :set_income, only: [:show, :edit, :update, :destroy]
  layout 'home'

  # GET /incomes
  # GET /incomes.json
  def index
    @incomes = current_user.incomes.all.order("created_at DESC")
  end

  # GET /incomes/1
  # GET /incomes/1.json
  def show
  end

  # GET /incomes/new
  def new
    @income = current_user.incomes.new
  end

  # GET /incomes/1/edit
  def edit
  end

  # POST /incomes
  # POST /incomes.json
  def create
    @income = current_user.incomes.new(income_params)

    respond_to do |format|
      if @income.save
        format.html { redirect_to @income, notice: 'Income was successfully created.' }
        format.json { render :show, status: :created, location: @income }
      else
        format.html { render :new }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incomes/1
  # PATCH/PUT /incomes/1.json
  def update
    respond_to do |format|
      if @income.update(income_params)
        format.html { redirect_to @income, notice: 'Income was successfully updated.' }
        format.json { render :show, status: :ok, location: @income }
      else
        format.html { render :edit }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incomes/1
  # DELETE /incomes/1.json
  def destroy
    @income.destroy
    respond_to do |format|
      format.html { redirect_to incomes_url, notice: 'Income was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_income
      @income = current_user.incomes.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def income_params
      params.require(:income).permit(:total, :description, :user_id)
    end
end

app/controllers/outcomes_controller.rb
class OutcomesController < ApplicationController
  before_action :set_outcome, only: [:show, :edit, :update, :destroy]
  before_action :get_categories, only: [:new, :edit, :create, :update]
  before_action :authenticate_user!

  layout "home"

  # GET /outcomes
  # GET /outcomes.json
  def index
    @outcomes = current_user.outcomes.all.order("created_at DESC")
  end

  # GET /outcomes/1
  # GET /outcomes/1.json
  def show
  end

  # GET /outcomes/new
  def new
    @outcome = current_user.outcomes.new
  end

  # GET /outcomes/1/edit
  def edit
  end

  # POST /outcomes
  # POST /outcomes.json
  def create
    @outcome = current_user.outcomes.new(outcome_params.merge(:category_id => params[:category]))

    respond_to do |format|
      if @outcome.save
        format.html { redirect_to @outcome, notice: 'Outcome was successfully created.' }
        format.json { render :show, status: :created, location: @outcome }
      else
        format.html { render :new }
        format.json { render json: @outcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /outcomes/1
  # PATCH/PUT /outcomes/1.json
  def update
    respond_to do |format|
      if @outcome.update(outcome_params.merge(:category_id => params[:category]))
        format.html { redirect_to @outcome, notice: 'Outcome was successfully updated.' }
        format.json { render :show, status: :ok, location: @outcome }
      else
        format.html { render :edit }
        format.json { render json: @outcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /outcomes/1
  # DELETE /outcomes/1.json
  def destroy
    @outcome.destroy
    respond_to do |format|
      format.html { redirect_to outcomes_url, notice: 'Outcome was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_outcome
      @outcome = current_user.outcomes.find(params[:id])
    end

    def get_categories
      @categories = Category.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def outcome_params
      params.require(:outcome).permit(:total, :description, :user_id, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/outcomes_helper.rb
module OutcomesHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <% if f.error_notification %>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.input :name,
                autofocus: true,
                input_html: { class: "form-control" }%>
  </div>

  <div class="form-group">
    <%= f.button :submit,
                  class: "btn btn-info"%>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to categories_path, class: "btn btn-secondary" do %>
<span class="fa fa-arrow-left"></span> Back
<% end %>

<%= link_to @category, class: "btn btn-success" do %>
  <span class="fa fa-eye"></span> Show
<% end %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table class="table table-hover table-striped table-borderless">
  <thead>
    <tr>
      <th>Name</th>
      <th>Action</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td>
          <%= link_to category, class: "btn btn-success" do %>
            <span class="fa fa-eye"></span>
          <% end %>
          <%= link_to edit_category_path(category), class: "btn btn-warning" do %>
            <span class="fa fa-pencil"></span>
          <% end %>
          <%= link_to category, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" do %>
            <span class="fa fa-eraser"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to  new_category_path, class: "btn btn-primary" do %>
  <span class="fa fa-plus"></span> New Category
<% end %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to categories_path, class: "btn btn-secondary" do %>
  <span class="fa fa-arrow-left"></span> Back
<% end %>

app/views/categories/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to categories_path, class: "btn btn-secondary" do %>
<span class="fa fa-arrow-left"></span> Back
<% end %>

<%= link_to edit_category_path(@category), class: "btn btn-warning" do %>
  <span class="fa fa-pencil"></span> Edit
<% end %>

app/views/home/index.html.erb
<% if user_signed_in? %>

  <h2>Quick Menu</h2>

  <%= link_to new_category_path, class: "btn btn-success" do %>
    <span class="fa fa-plus"></span> Add Category
  <% end %>

  <%= link_to new_income_path, class: "btn btn-primary" do %>
    <span class="fa fa-plus"></span> Add Income
  <% end %>

  <%= link_to new_outcome_path, class: "btn btn-warning" do %>
    <span class="fa fa-plus"></span> Add Outcome
  <% end %>

<% else %>
  Expense Manager
<% end %>

app/views/incomes/_form.html.erb
<%= simple_form_for(@income) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-group">
      <%= f.input :total,
                  autofocus: true,
                  input_html: { class: "form-control" } %>
    </div>

    <div class="form-group">
      <%= f.input :description,
                  input_html: { class: "form-control" } %>
    </div>

  <div class="form-group">
    <%= f.button :submit, class: "btn btn-info" %>
  </div>
<% end %>

app/views/incomes/edit.html.erb
<h1>Editing Income</h1>

<%= render 'form', income: @income %>

<%= link_to incomes_path, class: "btn btn-secondary" do %>
  <span class="fa fa-arrow-left"></span> Back
<% end %>

<%= link_to @income, class: "btn btn-success" do %>
  <span class: "fa fa-eye"></span> Show
<% end %>

app/views/incomes/index.html.erb
<h1>Incomes</h1>

<table class="table table-hover table-striped">
  <thead>
    <tr>
      <th>Total</th>
      <th>Date</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @incomes.each do |income| %>
      <tr>
        <td><%= income.total %></td>
        <td><%= income.created_at %></td>
        <td><%= income.description %></td>
        <td>
          <%= link_to income, class: "btn btn-success" do %>
            <span class="fa fa-eye"></span>
          <% end %>

          <%= link_to edit_income_path(income), class: "btn btn-warning" do %>
            <span class="fa fa-pencil"></span>
          <% end %>

          <%= link_to income, method: :delete, class: "btn btn-danger", data: { confirm: 'Are you sure?' } do %>
            <span class="fa fa-eraser"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_income_path, class: "btn btn-info" do %>
  <span class="fa fa-plus"></span> New Income
<% end %>

app/views/incomes/new.html.erb
<h1>New Income</h1>

<%= render 'form', income: @income %>

<%= link_to incomes_path, class: "btn btn-secondary" do %>
  <span class="fa fa-arrow-left"></span> Back
<% end %>

app/views/incomes/show.html.erb
<p>
  <strong>Total:</strong>
  <%= @income.total %>
</p>

<p>
  <strong>Description:</strong>
  <%= @income.description %>
</p>

<%= link_to incomes_path, class: "btn btn-secondary" do %>
  <span class="fa fa-arrow-left"></span> Back
<% end %>

<%= link_to edit_income_path(@income), class: "btn btn-warning" do %>
  <span class="fa fa-pencil"></span> Edit
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-secondary">
  <%= link_to "Expense Manager", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <% if user_signed_in? %>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Categories', categories_path, class: "nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to 'Income', incomes_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%=  link_to 'Outcome', outcomes_path, class: "nav-link" %>
      </li>
    </ul>
    <% end %>

    <ul class="navbar-nav nav mr-right">
      <li class="nav-link">
        <% if user_signed_in? %>
          <%= link_to current_user.email, edit_user_registration_path, class: "btn btn-secondary" %>
        <% else %>
          <%= link_to 'Sign In', new_user_session_path, class: "btn btn-secondary" %>
        <% end %>
      </li>
      <li class="nav-link">
        <% if user_signed_in? %>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
        <% else %>
          <%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-danger" %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_notification.html.erb
<div class="row">
  <div class="col-12">
    <% if flash[:notice] %>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>Holy guacamole!</strong> <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>

<% if flash[:alert] %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <strong>Holy guacamole!</strong> <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
  </div>
</div>

app/views/layouts/_sidebar.html.erb
<h2>Statistic</h2>
<table class="table table-responsive">
  <tr>
    <td>Total Income</td>
    <td><%= @income_sum %></td>
  </tr>

  <tr>
    <td>Total Outcome</td>
    <td><%= @outcome_sum %></td>
  </tr>

  <tr>
    <td>Balance</td>
    <td><%= @balance %></td>
  </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExpenseManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container" style="margin-top: 80px;">

          <%= render 'layouts/notification'%>
          
      <div class="row">
        <div class="col-2">

        </div>
        <div class="col-8">
          <%= yield %>
        </div>
        <div class="col-2">

        </div>
      </div> <!-- Row -->
    </div> <!-- Container -->
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExpenseManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container" style="margin-top: 80px;">

    <%= render 'layouts/notification' %>

      <% if user_signed_in? %>
      <div class="row">
        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
          <%= render 'layouts/sidebar'%>
        </div> <!-- sidebar -->
        <% end %>

        <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
              <%= yield %>
        </div>
      </div> <!-- Row -->
    </div> <!-- Container -->
  </body>
</html>

app/views/outcomes/_form.html.erb
<%= simple_form_for(@outcome) do |f| %>

  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-group">
      <%= f.input :total,
                  autofocus: true,
                  required: true,
                  input_html: { class: "form-control" } %>
    </div>

    <div class="form-group">
      <%= f.input :description,
                  required: true,
                  input_html: { class: "form-control" } %>
    </div>

    <div class="form-group">
      <select class="form-control" name="category" required>
        <option value="">Select Category</option>
        <% @categories.each do |category| %>
        <option value="<%= category.id %>"><%= category.name %></option>
        <% end %>
      </select>
    </div>

  <div class="form-group">
    <%= f.button :submit, class: "btn btn-info" %>
  </div>
<% end %>

app/views/outcomes/edit.html.erb
<h1>Editing Outcome</h1>

<%= render 'form', outcome: @outcome %>

<%= link_to outcomes_path, class: "btn btn-secondary" do %>
  <span class="fa fa-arrow-left"></span> Back
<% end %>

<%= link_to @outcome, class: "btn btn-success" do %>
  <span class="fa fa-eye"></span> Show
<% end %>

app/views/outcomes/index.html.erb
<h1>Outcomes</h1>

<table class="table table-hover table-striped">
  <thead>
    <tr>
      <th>Total</th>
      <th>Description</th>
      <th>Category</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @outcomes.each do |outcome| %>
      <tr>
        <td><%= outcome.total %></td>
        <td><%= outcome.description %></td>
        <td>
          <%
            id = outcome.category_id.to_i
          %>
          <%= Category.find(id).name %>
        </td>
        <td><%= outcome.created_at %></td>
        <td>
          <%= link_to outcome, class: "btn btn-success" do %>
            <span class="fa fa-eye"></span>
          <% end %>
          <%= link_to edit_outcome_path(outcome), class: "btn btn-warning" do %>
            <span class="fa fa-pencil"></span>
          <% end %>
          <%= link_to outcome, method: :delete, class: "btn btn-danger", data: { confirm: 'Are you sure?' } do %>
            <span class="fa fa-eraser"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_outcome_path, class: "btn btn-info" do %>
  <span class="fa fa-plus"></span> New Outcome
<% end %>

app/views/outcomes/new.html.erb
<h1>New Outcome</h1>

<%= render 'form', outcome: @outcome %>

<%= link_to outcomes_path, class: "btn btn-secondary" do %>
  <span class="fa fa-arrow-left"></span> Back
<% end %>

app/views/outcomes/show.html.erb
<p>
  <strong>Total:</strong>
  <%= @outcome.total %>
</p>

<p>
  <strong>Description:</strong>
  <%= @outcome.description %>
</p>
<p>
  <strong>Category</strong>
  <%= @outcome.category.name %>
</p>

<%= link_to outcomes_path, class: "btn btn-secondary" do %>
  <span class="fa fa-arrow-left"></span> Back
<% end %>

<%= link_to edit_outcome_path(@outcome), class: "btn btn-warning" do %>
  <span class="fa fa-pencil"></span> Edit
<% end %>